# Generated by Django 5.1.4 on 2025-01-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
