# Generated by Django 5.1.4 on 2025-02-10 20:35

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_contribution_contribution_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-contributed_at']},
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="List of contribution types (e.g., 'code', 'design').", size=None),
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('user', 'project')},
        ),
    ]
