# Generated by Django 5.1.4 on 2025-02-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_contribution_contribution_type'),
        ('social_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialdetails',
            unique_together={('project',)},
        ),
    ]
